x-kong-config: &kong-env
  KONG_DATABASE: postgres # Use Postgres as the backing database
  KONG_PG_HOST: ogna-database # Hostname of the Postgres service
  KONG_PG_DATABASE: ${POSTGRES_DB} # Name of the database to connect to
  KONG_PG_USER: ${POSTGRES_USER} # Database username
  KONG_PG_PASSWORD: ${POSTGRES_PASSWORD} # Database password

services:
  kong-bootstrap:
    image: "${GW_IMAGE:-kong/kong-gateway:3.12.0.0}" # Kong Gateway image (default to latest version)
    container_name: kong-bootstrap
    networks:
      - ogna
    depends_on:
      ogna-database:
        condition: service_healthy
    restart: on-failure
    environment:
      <<: *kong-env
      KONG_PASSWORD: handyshake # Admin GUI password (required for RBAC)

    command: kong migrations bootstrap # Run DB migrations to initialize Kong schema

  kong-cp:
    image: kong/kong-gateway:3.12.0.0
    container_name: kong-cp
    restart: on-failure
    networks:
      - ogna
    environment:
      <<: *kong-env
      KONG_PLUGINS: bundled,acme,cors
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PASSWORD: handyshake
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
      KONG_NGINX_HTTP_LUA_SHARED_DICT: acme_storage 10m
      #KONG_DECLARATIVE_CONFIG: /kong/kong.yaml
    depends_on:
      kong-bootstrap:
        condition: service_completed_successfully # Start only after bootstrap has succeeded
      ogna-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001" # Keep for internal access only
    volumes:
      - ./config/kong.yaml:/kong/kong.yaml:ro
      - ./acme:/usr/local/kong/acme
    env_file:
      - .env

  ogna-database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - ogna
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ogna_user", "-d", "ogna_db"]
      interval: 5s
      timeout: 10s
      retries: 10
    env_file:
      - .env

  deck-sync:
    image: kong/deck:latest
    depends_on:
      kong-cp:
        condition: service_healthy
    networks:
      - ogna
    volumes:
      - ./config:/kong-extra
    command:
      [
        "gateway",
        "sync",
        "--kong-addr",
        "http://kong-cp:8001",
        "/kong-extra/kong.yaml",
      ]

volumes:
  postgres_data:
  acme_storage:

networks:
  ogna:
    name: ogna
    driver: bridge
