services:
  traefik:
    image: traefik:v3.5.3
    container_name: traefik
    restart: unless-stopped
    command:
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Enable Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # ACME / Let's Encrypt config
      - "--certificatesresolvers.hetzner.acme.email=${EMAIL}"
      - "--certificatesresolvers.hetzner.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.hetzner.acme.dnschallenge=true"
      - "--certificatesresolvers.hetzner.acme.dnschallenge.provider=hetzner"

      - "--log.level=DEBUG"

    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - ogna

networks:
  ogna:
    name: ogna
    driver: bridge
  databases:
    name: databases
    driver: bridge
