x-kong-config: &kong-env
  KONG_DATABASE: postgres
  KONG_PG_HOST: ogna-database
  KONG_PG_DATABASE: ${POSTGRES_DB}
  KONG_PG_USER: ${POSTGRES_USER}
  KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}

services:
  kong-bootstrap:
    image: kong/kong-gateway:3.12.0.0
    container_name: kong-bootstrap
    networks:
      - ogna
    depends_on:
      ogna-database:
        condition: service_healthy
    restart: on-failure
    environment:
      <<: *kong-env
    command: kong migrations bootstrap

  kong-cp:
    image: kong/kong-gateway:3.12.0.0
    container_name: kong-cp
    restart: unless-stopped
    networks:
      - ogna
    environment:
      <<: *kong-env
      KONG_PLUGINS: bundled,acme,cors
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
      KONG_NGINX_HTTP_LUA_SHARED_DICT: acme_storage 10m
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_SSL_CERT: /etc/letsencrypt/live/${DOMAIN}/fullchain.pem
      KONG_SSL_CERT_KEY: /etc/letsencrypt/live/${DOMAIN}/privkey.pem
      KONG_HEADERS: "off"
      KONG_SERVER_TOKENS: "off"
      KONG_NGINX_WORKER_PROCESSES: ${KONG_WORKER_PROCESSES:-auto}
      KONG_NGINX_WORKER_CONNECTIONS: ${KONG_WORKER_CONNECTIONS:-4096}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: ${KONG_LOG_LEVEL:-notice}
    depends_on:
      kong-bootstrap:
        condition: service_completed_successfully
      ogna-database:
        condition: service_healthy
      certbot:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    ports:
      - "80:8000"
      - "443:8443"
    volumes:
      - ./config/kong.yaml:/kong/kong.yaml:ro
      - ./acme:/usr/local/kong/acme
      - ./certs:/etc/letsencrypt:ro # shared bind mount
      - ./logs:/var/log/kong
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 512M
    env_file:
      - .env

  ogna-database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - ogna
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-ogna_user} -d ${POSTGRES_DB:-ogna_db}",
        ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    env_file:
      - .env

  deck-sync:
    image: kong/deck:latest
    depends_on:
      kong-cp:
        condition: service_healthy
    networks:
      - ogna
    volumes:
      - ./config:/kong-extra
    command:
      [
        "gateway",
        "sync",
        "--kong-addr",
        "http://kong-cp:8001",
        "/kong-extra/kong.yaml",
      ]

  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    container_name: certbot
    restart: no
    volumes:
      - ./certs:/etc/letsencrypt # shared with Kong
      - ./certbot-logs:/var/log/letsencrypt
      - ./scripts:/scripts
    command:
      - certonly
      - --authenticator=dns-hetzner
      - --dns-hetzner-credentials=/scripts/hetzner.ini
      - -d
      - "*.${DOMAIN}"
      - --email=${EMAIL}
      - --agree-tos
      - --non-interactive
      - --keep-until-expiring
    networks:
      - ogna
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local

networks:
  ogna:
    name: ogna
    driver: bridge
