services:
  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    container_name: certbot
    restart: no
    volumes:
      - ./certs:/etc/letsencrypt
      - ./scripts:/scripts
    command:
      - -c
      - |
        certbot certonly \
          --authenticator dns-hetzner \
          --dns-hetzner-credentials /scripts/hetzner.ini \
          -d "*.user.$DOMAIN" \
          -d "user.$DOMAIN" \
          --email "$EMAIL" \
          --agree-tos \
          --non-interactive \
          --keep-until-expiring
        trap exit TERM
    networks:
      - ogna
    env_file:
      - .env
networks:
  ogna:
    name: ogna
    driver: bridge
