
_format_version: "3.0"

# Admin protection
consumers:
  - username: admin
    keyauth_credentials:
      - key: b05de7230d996ef08ccc7af18a079f88f031eaa8f2db1347b64758fbf6d852c8

# Protect Kong's own Admin API via proxy
services:
  - name: admin-api
    url: http://kong-cp:8001
    routes:
      - name: admin-api-route
        paths:
          - /admin
    plugins:
      - name: key-auth

